const N=10, boardEl=document.querySelector('#board'), piecesEl=document.querySelector('#pieces');
let board=[], pieces=[], selected=-1, score=0, sound=true;
const SHAPES=[[[0,0]],[[0,0],[1,0]],[[0,0],[1,0],[2,0]],[[0,0],[0,1]],[[0,0],[0,1],[0,2]],[[0,0],[1,0],[0,1]],[[0,0],[1,0],[1,1]],[[0,0],[0,1],[1,1]],[[1,0],[0,1],[1,1]],[[0,0],[1,0],[0,1],[1,1]],[[0,0],[1,0],[2,0],[3,0]],[[0,0],[0,1],[0,2],[0,3]],[[0,0],[1,0],[2,0],[1,1]],[[0,0],[1,0],[2,0],[0,1]],[[0,0],[0,1],[1,1],[2,1]],[[0,0],[1,0],[2,0],[0,1],[1,1],[2,1],[0,2],[1,2],[2,2]]];
function tone(f=440,d=.06){if(!sound)return;try{let a=new AudioContext(),o=a.createOscillator(),g=a.createGain();o.frequency.value=f;g.gain.value=.035;o.connect(g);g.connect(a.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,a.currentTime+d);o.stop(a.currentTime+d)}catch(e){}}
function reset(){board=Array(N*N).fill(0);score=0;selected=-1;newPieces();document.querySelector('#modal').classList.add('hidden');render();}
function newPieces(){pieces=Array.from({length:3},()=>SHAPES[Math.floor(Math.random()*SHAPES.length)]);}
function valid(shape,x,y){return shape.every(([dx,dy])=>x+dx<N&&y+dy<N&&!board[(y+dy)*N+x+dx]);}
function anyMove(){return pieces.some(s=>s&&Array.from({length:N},(_,y)=>y).some(y=>Array.from({length:N},(_,x)=>x).some(x=>valid(s,x,y))));}
function place(i,x,y){let s=pieces[i];if(!s||!valid(s,x,y)){tone(150,.08);return}s.forEach(([dx,dy])=>board[(y+dy)*N+x+dx]=1);score+=s.length;pieces[i]=null;selected=-1;clearLines();if(pieces.every(x=>!x))newPieces();render();tone(560);if(!anyMove())gameOver();}
function clearLines(){let rows=[],cols=[];for(let y=0;y<N;y++)if(board.slice(y*N,y*N+N).every(Boolean))rows.push(y);for(let x=0;x<N;x++){let ok=true;for(let y=0;y<N;y++)if(!board[y*N+x])ok=false;if(ok)cols.push(x)}if(rows.length||cols.length){rows.forEach(y=>{for(let x=0;x<N;x++)board[y*N+x]=0});cols.forEach(x=>{for(let y=0;y<N;y++)board[y*N+x]=0});let lines=rows.length+cols.length;score+=lines*10+Math.max(0,lines-1)*10;tone(820,.12)}}
function gameOver(){let best=Math.max(score,+localStorage.getItem('matterOriBest')||0);localStorage.setItem('matterOriBest',best);document.querySelector('#best').textContent=best;document.querySelector('#final').textContent=score;document.querySelector('#modal').classList.remove('hidden');tone(120,.2)}
function render(){boardEl.innerHTML='';for(let y=0;y<N;y++)for(let x=0;x<N;x++){let c=document.createElement('div');c.className='cell'+(board[y*N+x]?' filled':'');c.onclick=()=>selected>=0&&place(selected,x,y);c.onmouseenter=()=>preview(x,y);boardEl.appendChild(c)}document.querySelector('#score').textContent=score;document.querySelector('#best').textContent=Math.max(score,+localStorage.getItem('matterOriBest')||0);piecesEl.innerHTML='';pieces.forEach((s,i)=>{let p=document.createElement('div');p.className='piece'+(selected===i?' selected':'');if(s){let mx=Math.max(...s.map(q=>q[0]))+1,my=Math.max(...s.map(q=>q[1]))+1,m=document.createElement('div');m.className='mini';m.style.gridTemplateColumns=`repeat(${mx},17px)`;for(let y=0;y<my;y++)for(let x=0;x<mx;x++){let q=document.createElement('i');if(!s.some(([a,b])=>a===x&&b===y))q.className='off';m.appendChild(q)}p.appendChild(m);p.onclick=()=>{selected=i;render()}}piecesEl.appendChild(p)})}
function preview(x,y){document.querySelectorAll('.cell').forEach((c,i)=>c.className='cell'+(board[i]?' filled':''));if(selected<0||!pieces[selected])return;let ok=valid(pieces[selected],x,y);pieces[selected].forEach(([dx,dy])=>{if(x+dx<N&&y+dy<N){let c=boardEl.children[(y+dy)*N+x+dx];if(c&&!board[(y+dy)*N+x+dx])c.classList.add(ok?'preview':'bad')}})}
document.querySelector('#restart').onclick=reset;document.querySelector('#again').onclick=reset;document.querySelector('#sound').onclick=e=>{sound=!sound;e.target.textContent='Sound: '+(sound?'On':'Off')};reset();
